In [5]:
import cv2
import numpy as np
from PIL import Image
from sklearn.cluster import KMeans
import random

pixels = list()
image_path = "/Users/vinaykumar/Downloads/medibuddy_images/combigan_2.webp"
img = cv2.imread(image_path)

def adjust_color(color, degree_change):
    """
    Adjusts the RGB values of the given color by a random amount within the specified degree.
    """
    adjusted_color = []
    for value in color:
        change = random.randint(-degree_change, degree_change)
        adjusted_value = np.clip(value + change, 0, 255)
        adjusted_color.append(adjusted_value)
    return tuple(adjusted_color)

def identify_target_colors(img, num_colors):
    img_array = np.array(img)
    pixels = img_array.reshape(-1, 3)
    kmeans = KMeans(n_clusters=num_colors)
    kmeans.fit(pixels)
    target_colors = kmeans.cluster_centers_.astype(int)
    return target_colors

def calculate_color_frequencies(image, target_colors):
    color_frequencies = {tuple(color): 0 for color in target_colors}
    total_count = 0
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            pixel_color = tuple(image[i, j])
            if pixel_color in color_frequencies:
                color_frequencies[pixel_color] += 1
                total_count += 1
    color_ratios = {color: freq / total_count for color, freq in color_frequencies.items()}
    return color_ratios

def unique_brand_to_target_mapping(target_colors, degree_change):
    unique_mapping = {}
    used_targets = set()
    for brand_color, (target_color, distance) in sorted(initial_mapping.items(), key=lambda x: x[1][1]):
        if target_color not in used_targets:
            adjusted_color = adjust_color(target_color, degree_change)
            unique_mapping[brand_color] = adjusted_color
            used_targets.add(adjusted_color)
    return unique_mapping

# Rest of your code remains the same
num_colors = 3  # Number of target colors
target_colors = identify_target_colors(img, num_colors)
# New part: Adjusting the colors
degree_change = 10  # Degree of color change
# Degree of color change
degree_change = 10


# Create a dictionary to map original colors to adjusted colors
color_mapping = {}
for color in target_colors:
    adjusted_color = adjust_color(color, degree_change)
    color_mapping[tuple(color)] = adjusted_color

# Print the color mapping
for original, adjusted in color_mapping.items():
    print(f"Original Color: {original} -> Adjusted Color: {adjusted}")


/usr/local/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


Original Color: (242, 241, 248) -> Adjusted Color: (240, 239, 251)
Original Color: (95, 31, 56) -> Adjusted Color: (90, 26, 52)
Original Color: (172, 146, 173) -> Adjusted Color: (173, 136, 166)


In [ ]:
color_mapping

In [4]:
import cv2
import numpy as np
import random

def add_gaussian_noise(image, mean=0, std=25):
    """Add Gaussian noise to the image."""
    noise = np.random.normal(mean, std, image.shape).astype(np.uint8)
    noisy_image = cv2.add(image, noise)
    return noisy_image

def adjust_brightness_contrast(image, alpha=1.2, beta=5):
    """Adjust the brightness and contrast of the image."""
    adjusted_image = cv2.convertScaleAbs(image, alpha=alpha, beta=beta)
    return adjusted_image

def apply_gaussian_blur(image, kernel_size=(5, 5)):
    """Apply Gaussian blur to the image."""
    blurred_image = cv2.GaussianBlur(image, kernel_size, 0)
    return blurred_image

def apply_multiple_techniques(image_path):
    # Read the image
    img = cv2.imread(image_path)

    # # Apply multiple techniques
    # if random.choice([True, False]):
    #     img = add_gaussian_noise(img, mean=0, std=25)

    img = adjust_brightness_contrast(img, alpha=1.2, beta=10)

    # if random.choice([True, False]):
    #     img = apply_gaussian_blur(img, kernel_size=(5, 5))

    # Save the modified image
    cv2.imwrite("/Users/vinaykumar/Downloads/test.png", img)

# Specify the path to your image
image_path = "/Users/vinaykumar/Downloads/medibuddy_images/combigan_2.webp"

# Apply multiple techniques and save the modified image
apply_multiple_techniques(image_path)


In [29]:
import cv2
import numpy as np
import random
import os
import glob

def random_color_adjustment(image):
    """Apply random color adjustment to the image."""
    # Randomly adjust brightness, contrast, and saturation
    alpha = random.uniform(0.7, 1.3)  # Brightness/Contrast adjustment factor
    beta = random.randint(-20, 20)    # Brightness adjustment value
    saturation_factor = random.uniform(0.7, 1.3)  # Saturation adjustment factor

    # Convert image to HSV color space
    hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    # Apply adjustments
    hsv_image[:, :, 2] = np.clip(alpha * hsv_image[:, :, 2] + beta, 0, 255)
    hsv_image[:, :, 1] = np.clip(saturation_factor * hsv_image[:, :, 1], 0, 255)

    # Convert back to BGR color space
    adjusted_image = cv2.cvtColor(hsv_image, cv2.COLOR_HSV2BGR)
    return adjusted_image

def make_image_darker(image):
    """Reduce the brightness of the image to make it darker."""
    brightness_factor = random.uniform(0.8, 1)  # Adjust this for darkness level
    darkened_image = (image * brightness_factor).astype(np.uint8)
    return darkened_image


def add_watermark(input_image, watermark_image_path, scale_factor = 0.5):
    # Read the input image and watermark image
    
    watermark = cv2.imread(watermark_image_path, cv2.IMREAD_UNCHANGED)

    # Get the dimensions of the watermark image
    wm_h, wm_w = watermark.shape[:2]

    # Resize the watermark based on the scale factor
    watermark = cv2.resize(watermark, (int(wm_w * scale_factor), int(wm_h * scale_factor)))

    # Get the updated dimensions of the watermark
    wm_h, wm_w = watermark.shape[:2]
    
    # Define the position to place the watermark (top-left corner)
    position = (10, 10)  # Adjust the position as needed

    # Extract the alpha channel (transparency) from the watermark
    alpha_channel = watermark[:, :, 3]

    # Create a region of interest (ROI) in the input image for placing the watermark
    roi = input_image[position[1]:position[1] + wm_h, position[0]:position[0] + wm_w]
    
    print (roi)
    print (wm_h, wm_w)
    
    # Blend the resized watermark with the ROI using the alpha channel
    for c in range(0, 3):
        print (watermark[:, :, c])
        input_image[position[1]:position[1] + wm_h, position[0]:position[0] + wm_w, c] = \
            input_image[position[1]:position[1] + wm_h, position[0]:position[0] + wm_w, c] * \
            (1 - alpha_channel / 255.0) + watermark[:, :, c] * (alpha_channel / 255.0)

    return input_image


# Folder path containing image files
folder_path = "/Users/vinaykumar/Downloads/medibuddy_images"

# List all image files in the folder (supports common image formats like JPG, PNG, etc.)
image_files = glob.glob(os.path.join(folder_path, "*.webp"))

# Path to the watermark image
watermark_path = "/Users/vinaykumar/Downloads/medibuddy_logo.png"

# Process each image
for image_path in image_files:
    img = cv2.imread(image_path)

    # Apply random color adjustment
    img = random_color_adjustment(img)

    # Make the image darker
    img = make_image_darker(img)

    # Add watermark to the image
    img_with_watermark = add_watermark(img, watermark_path)

    # Save the modified image with watermark in the same folder
    filename = os.path.basename(image_path)
    output_image_path = os.path.join(folder_path, filename.replace(".webp", "_modified_with_watermark.jpg"))
    cv2.imwrite(output_image_path, img_with_watermark)

[[[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [216 216 216]
  [216 216 216]
  [216 216 216]]

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [216 216 216]
  [216 216 216]
  [216 216 216]]

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [216 216 216]
  [216 216 216]
  [216 216 216]]

 ...

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [182 178 167]
  [181 177 167]
  [179 179 167]]

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [184 177 167]
  [183 179 168]
  [181 177 167]]

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [176 169 158]
  [181 176 165]
  [181 177 167]]]
81 155
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[